from question_generation.methods.template.question_types.inferential.comparison import ComparisonQuestion
from question_generation.methods.template.question_types.inferential.chain import ChainQuestion
from question_generation.methods.template.question_types.inferential.subgraph import SubgraphQuestion
from question_generation.methods.template.question_types.inferential.chain_subgraph import ChainSubgraphQuestion
from question_generation.methods.template.question_types.inferential.bridge import BridgeQuestion

TYPES = [ComparisonQuestion, ChainQuestion, SubgraphQuestion, ChainSubgraphQuestion, BridgeQuestion]
